const CORPUS = new Map([
  ["100", {"code":"100","names":"curcumins","type":"colour","status":"a e u"}],
  ["100(i)", {"code":"100(i)","names":"curcumin","type":"colour (yellow and orange)","status":"a e u"}],
  ["100(ii)", {"code":"100(ii)","names":"turmeric","type":"colour (yellow and orange)","status":"a e u"}],
  ["101", {"code":"101","names":"riboflavins","type":"","status":"a e"}],
  ["101(i)", {"code":"101(i)","names":"riboflavin, synthetic (vitamin B2)","type":"colour (yellow and orange)","status":"a e"}],
  ["101(ii)", {"code":"101(ii)","names":"Riboflavin-5'-phosphate","type":"colour (yellow and orange)","status":"a e"}],
  ["101(iii)", {"code":"101(iii)","names":"riboflavin from Bacillus subtilis","type":"colour (yellow and orange)","status":"a e"}],
  ["102", {"code":"102","names":"tartrazine","type":"colour (yellow and orange) (FDA: FD&C Yellow #5)","status":"a e"}],
  ["103", {"code":"103","names":"alkannin, chrysoine resorcinol","type":"colour (red)","status":"a"}],
  ["104", {"code":"104","names":"Quinoline Yellow WS","type":"colour (yellow and orange) (FDA: D&C Yellow #10)","status":"a e"}],
  ["107", {"code":"107","names":"Yellow 2G","type":"colour (yellow and orange)","status":"e"}],
  ["110", {"code":"110","names":"Sunset Yellow FCF","type":"colour (yellow and orange) (FDA: FD&C Yellow #6)","status":"a e"}],
  ["111", {"code":"111","names":"Orange GGN. Delisted","type":"colour (orange)","status":"e"}],
  ["120", {"code":"120","names":"Cochineal, carmines","type":"colour (red)","status":"a e"}],
  ["121", {"code":"121","names":"Citrus red 2, Orcein, Orchil","type":"colour (red)","status":""}],
  ["122", {"code":"122","names":"azorubine, carmoisine","type":"colour (red) (FDA: Ext D&C Red #10)","status":"a e"}],
  ["123", {"code":"123","names":"amaranth","type":"colour (red) (FDA: [DELISTED] Red #2)","status":"e"}],
  ["124", {"code":"124","names":"Brilliant Scarlet 4R, Ponceau 4R","type":"colour (FDA: Ext D&C Red #8)","status":"a e"}],
  ["125", {"code":"125","names":"Ponceau SX, Scarlet GN","type":"colour","status":""}],
  ["126", {"code":"126","names":"Ponceau 6R. Delisted","type":"colour","status":""}],
  ["127", {"code":"127","names":"erythrosine","type":"colour (red) (FDA: FD&C Red #3)","status":"e"}],
  ["128", {"code":"128","names":"Red 2G","type":"colour","status":"e"}],
  ["129", {"code":"129","names":"Allura red AC","type":"colour (FDA: FD&C Red #40)","status":"a e"}],
  ["130", {"code":"130","names":"Indanthrene blue RS","type":"colour (blue)","status":""}],
  ["131", {"code":"131","names":"Patent blue V","type":"colour (blue)","status":"e"}],
  ["132", {"code":"132","names":"indigo carmine, indigotine","type":"colour (blue) (FDA: FD&C Blue #2)","status":"a e"}],
  ["133", {"code":"133","names":"Brilliant blue FCF","type":"colour (FDA: FD&C Blue #1)","status":"a e"}],
  ["140", {"code":"140","names":"chlorophylls","type":"colour (green)","status":"a e"}],
  ["141", {"code":"141","names":"Chlorophylls and chlorophyllins, copper complexes","type":"","status":"a e"}],
  ["141(i)", {"code":"141(i)","names":"Chlorophylls, copper complexes","type":"colour (green)","status":""}],
  ["141(ii)", {"code":"141(ii)","names":"Chlorophyllins, copper complexes, potassium and sodium salts","type":"colour (green)","status":""}],
  ["142", {"code":"142","names":"Green S","type":"colour (green)","status":"a e"}],
  ["143", {"code":"143","names":"Fast green FCF","type":"colour (FDA: FD&C Green #3)","status":"a e"}],
  ["150", {"code":"150","names":"Caramels","type":"","status":"a e"}],
  ["150a", {"code":"150a","names":"caramel I – plain","type":"colour (brown and black)","status":"a e"}],
  ["150b", {"code":"150b","names":"caramel II – sulfite caramel","type":"colour (brown and black)","status":"a e"}],
  ["150c", {"code":"150c","names":"caramel III – ammonia caramel","type":"colour (brown and black)","status":"a e"}],
  ["150d", {"code":"150d","names":"caramel IV – sulfite ammonia caramel","type":"colour (brown and black)","status":"a e"}],
  ["151", {"code":"151","names":"Brilliant Black BN (Black PN)","type":"colour (brown and black)","status":"a e"}],
  ["152", {"code":"152","names":"Carbon black","type":"colour (brown and black)","status":""}],
  ["153", {"code":"153","names":"Vegetable carbon","type":"colour (brown and black)","status":"a e"}],
  ["154", {"code":"154","names":"Brown FK","type":"colour (brown and black)","status":"e"}],
  ["155", {"code":"155","names":"Chocolate Brown HT","type":"colour","status":"a e"}],
  ["160a", {"code":"160a","names":"carotenes","type":"","status":"a e"}],
  ["160a(i)", {"code":"160a(i)","names":"beta-carotene, synthetic","type":"colour","status":"a e"}],
  ["160a(ii)", {"code":"160a(ii)","names":"beta-carotene, vegetable","type":"colour","status":"a e"}],
  ["160a(iii)", {"code":"160a(iii)","names":"beta-carotene, Blakeslea trispora","type":"colour","status":"a e"}],
  ["160a(iv)", {"code":"160a(iv)","names":"beta-carotene, algae","type":"colour","status":"a e"}],
  ["160b", {"code":"160b","names":"annatto extracts","type":"","status":"e"}],
  ["160b(i)", {"code":"160b(i)","names":"annatto extracts, bixin-based","type":"colour","status":"e"}],
  ["160b(ii)", {"code":"160b(ii)","names":"annatto extracts, norbixin-based","type":"colour","status":"e"}],
  ["160c", {"code":"160c","names":"paprika oleoresin (paprika extract)","type":"colour","status":"a e"}],
  ["160d", {"code":"160d","names":"lycopenes","type":"","status":"a e"}],
  ["160d(i)", {"code":"160d(i)","names":"lycopene, synthetic","type":"colour","status":"a e"}],
  ["160d(ii)", {"code":"160d(ii)","names":"lycopene, tomato","type":"colour","status":"a e"}],
  ["160d(iii)", {"code":"160d(iii)","names":"lycopene, Blakeslea trispora","type":"colour","status":"a e"}],
  ["160e", {"code":"160e","names":"beta-apo-8'-carotenal (C 30)","type":"colour","status":"a e"}],
  ["160f", {"code":"160f","names":"beta-apo-8'-carotenic acid ethyl ester","type":"colour","status":"a e"}],
  ["161a", {"code":"161a","names":"flavoxanthin","type":"colour","status":"a"}],
  ["161b", {"code":"161b","names":"luteins","type":"","status":"a e"}],
  ["161b(i)", {"code":"161b(i)","names":"lutein from Tagetes erecta","type":"colour","status":"a e"}],
  ["161b(ii)", {"code":"161b(ii)","names":"Tagetes extract","type":"colour","status":"a e"}],
  ["161c", {"code":"161c","names":"kryptoxanthin","type":"colour","status":"a"}],
  ["161d", {"code":"161d","names":"rubixanthin","type":"colour","status":"a"}],
  ["161e", {"code":"161e","names":"violaxanthin","type":"colour","status":"a"}],
  ["161f", {"code":"161f","names":"rhodoxanthin","type":"colour","status":"a"}],
  ["161g", {"code":"161g","names":"canthaxanthin","type":"colour","status":"e"}],
  ["161h", {"code":"161h","names":"zeaxanthins","type":"colour","status":""}],
  ["161h(i)", {"code":"161h(i)","names":"zeaxanthin, synthetic","type":"colour","status":""}],
  ["161h(ii)", {"code":"161h(ii)","names":"zeaxanthin-rich extract from Tagetes erecta","type":"colour","status":""}],
  ["161i", {"code":"161i","names":"citranaxanthin. Delisted","type":"colour","status":""}],
  ["161j", {"code":"161j","names":"astaxanthin. Delisted","type":"colour","status":""}],
  ["162", {"code":"162","names":"beet red","type":"colour","status":"a e"}],
  ["163", {"code":"163","names":"anthocyanins","type":"colour","status":"a e"}],
  ["163(ii)", {"code":"163(ii)","names":"Grape skin extract","type":"colour","status":"a e"}],
  ["163(iii)", {"code":"163(iii)","names":"Blackcurrant extract","type":"colour","status":"a e"}],
  ["163(iv)", {"code":"163(iv)","names":"Purple corn colour","type":"colour","status":"a e"}],
  ["163(v)", {"code":"163(v)","names":"Red cabbage colour","type":"colour","status":"a e"}],
  ["164", {"code":"164","names":"Gardenia yellow","type":"","status":"a"}],
  ["165", {"code":"165","names":"Gardenia blue","type":"colour","status":""}],
  ["166", {"code":"166","names":"sandalwood","type":"colour","status":""}],
  ["170", {"code":"170","names":"calcium carbonates","type":"","status":"e"}],
  ["170(i)", {"code":"170(i)","names":"calcium carbonate","type":"Acidity regulator, anticaking agent, stabilizer, surface colourant","status":"e"}],
  ["170(ii)", {"code":"170(ii)","names":"calcium hydrogen carbonate","type":"Acidity regulator, anticaking agent, stabilizer, surface colourant","status":"e"}],
  ["171", {"code":"171","names":"titanium dioxide","type":"colour (white)","status":"a e"}],
  ["172", {"code":"172","names":"iron oxides","type":"","status":"a e"}],
  ["172(i)", {"code":"172(i)","names":"iron oxide, black","type":"colour","status":"a e"}],
  ["172(ii)", {"code":"172(ii)","names":"iron oxide, red","type":"colour","status":"a e"}],
  ["172(iii)", {"code":"172(iii)","names":"iron oxide, yellow","type":"colour","status":"a e"}],
  ["173", {"code":"173","names":"aluminium","type":"colour (silver)","status":"e"}],
  ["174", {"code":"174","names":"silver","type":"colour (silver)","status":"e"}],
  ["175", {"code":"175","names":"gold","type":"colour (gold)","status":"e"}],
  ["180", {"code":"180","names":"Lithol Rubine BK","type":"colour","status":"e"}],
  ["181", {"code":"181","names":"tannins","type":"colour, emulsifier, stabiliser, thickener","status":"e"}],
  ["182", {"code":"182","names":"orchil","type":"colour","status":""}],
  ["200", {"code":"200","names":"sorbic acid","type":"preservative","status":"e"}],
  ["201", {"code":"201","names":"sodium sorbate","type":"preservative","status":""}],
  ["202", {"code":"202","names":"potassium sorbate","type":"preservative","status":"e"}],
  ["203", {"code":"203","names":"calcium sorbate","type":"preservative","status":"e"}],
  ["209", {"code":"209","names":"heptyl p-hydroxybenzoate","type":"preservative","status":""}],
  ["210", {"code":"210","names":"benzoic acid","type":"preservative","status":"e"}],
  ["211", {"code":"211","names":"sodium benzoate","type":"preservative","status":"a e"}],
  ["212", {"code":"212","names":"potassium benzoate","type":"preservative","status":"a e"}],
  ["213", {"code":"213","names":"calcium benzoate","type":"preservative","status":"a e"}],
  ["214", {"code":"214","names":"ethyl para-hydroxybenzoate","type":"preservative","status":"e"}],
  ["215", {"code":"215","names":"sodium ethyl para-hydroxybenzoate","type":"preservative","status":"e"}],
  ["216", {"code":"216","names":"propylparaben (propyl para-hydroxybenzoate)","type":"preservative","status":"a"}],
  ["217", {"code":"217","names":"sodium propyl para-hydroxybenzoate","type":"preservative","status":""}],
  ["218", {"code":"218","names":"methylparaben (methyl para-hydroxybenzoate)","type":"preservative","status":"a e"}],
  ["219", {"code":"219","names":"sodium methyl para-hydroxybenzoate","type":"preservative","status":"e"}],
  ["220", {"code":"220","names":"sulfur dioxide","type":"preservative, antioxidant","status":"a e"}],
  ["221", {"code":"221","names":"sodium sulfite","type":"preservative, antioxidant","status":"a e"}],
  ["222", {"code":"222","names":"sodium bisulfite (sodium hydrogen sulfite)","type":"preservative, antioxidant","status":"a e"}],
  ["223", {"code":"223","names":"sodium metabisulfite","type":"preservative, antioxidant, bleaching agent","status":"a e"}],
  ["224", {"code":"224","names":"potassium metabisulfite","type":"preservative, antioxidant","status":"a e"}],
  ["225", {"code":"225","names":"potassium sulfite","type":"preservative, antioxidant","status":"a"}],
  ["226", {"code":"226","names":"calcium sulfite","type":"preservative, antioxidant","status":"e"}],
  ["227", {"code":"227","names":"calcium bisulfite, calcium hydrogen sulfite","type":"preservative, antioxidant","status":"e"}],
  ["228", {"code":"228","names":"potassium bisulfite, potassium hydrogen sulfite","type":"preservative, antioxidant","status":"a e"}],
  ["230", {"code":"230","names":"diphenyl (biphenyl)","type":"preservative","status":"e"}],
  ["231", {"code":"231","names":"orthophenyl phenol (2-hydroxybiphenyl)","type":"preservative","status":"e"}],
  ["232", {"code":"232","names":"sodium orthophenyl phenol","type":"preservative","status":"e"}],
  ["233", {"code":"233","names":"thiabendazole","type":"preservative","status":""}],
  ["234", {"code":"234","names":"nisin","type":"preservative","status":"a e"}],
  ["235", {"code":"235","names":"natamycin (pimaricin)","type":"preservative","status":"a e"}],
  ["236", {"code":"236","names":"formic acid","type":"preservative","status":""}],
  ["237", {"code":"237","names":"sodium formate","type":"preservative","status":""}],
  ["238", {"code":"238","names":"calcium formate","type":"preservative","status":""}],
  ["239", {"code":"239","names":"hexamethylene tetramine (hexamine)","type":"preservative","status":"e"}],
  ["240", {"code":"240","names":"formaldehyde","type":"preservative","status":""}],
  ["241", {"code":"241","names":"gum guaicum","type":"preservative","status":""}],
  ["242", {"code":"242","names":"dimethyl dicarbonate","type":"preservative","status":"a e"}],
  ["249", {"code":"249","names":"potassium nitrite","type":"preservative, colour fixative","status":"a e"}],
  ["250", {"code":"250","names":"sodium nitrite","type":"preservative, colour fixative","status":"a e"}],
  ["251", {"code":"251","names":"sodium nitrate","type":"preservative, colour fixative","status":"a e"}],
  ["252", {"code":"252","names":"potassium nitrate","type":"preservative, colour fixative","status":"a"}],
  ["260", {"code":"260","names":"glacial acetic acid","type":"preservative, acidity regulator","status":"a e"}],
  ["261", {"code":"261","names":"potassium acetates","type":"preservative, acidity regulator","status":"a e"}],
  ["262", {"code":"262","names":"sodium acetate, sodium hydrogen acetate","type":"preservative, acidity regulator","status":"a e"}],
  ["263", {"code":"263","names":"calcium acetate","type":"preservative, acidity regulator","status":"a e"}],
  ["264", {"code":"264","names":"ammonium acetate","type":"preservative, acidity regulator","status":"a"}],
  ["265", {"code":"265","names":"dehydroacetic acid","type":"preservative","status":""}],
  ["266", {"code":"266","names":"sodium dehydroacetate","type":"preservative","status":""}],
  ["270", {"code":"270","names":"lactic acid","type":"acidity regulator, preservative, antioxidant","status":"a e"}],
  ["280", {"code":"280","names":"propionic acid","type":"preservative","status":"a e"}],
  ["281", {"code":"281","names":"sodium propionate","type":"preservative","status":"a e"}],
  ["282", {"code":"282","names":"calcium propionate","type":"preservative","status":"a e"}],
  ["283", {"code":"283","names":"potassium propionate","type":"preservative","status":"a e"}],
  ["284", {"code":"284","names":"boric acid","type":"preservative","status":"e"}],
  ["285", {"code":"285","names":"sodium tetraborate, borax","type":"preservative","status":"e"}],
  ["290", {"code":"290","names":"carbon dioxide","type":"acidity regulator, propellant","status":"a e"}],
  ["296", {"code":"296","names":"malic acid","type":"acidity regulator","status":"a e"}],
  ["297", {"code":"297","names":"fumaric acid","type":"acidity regulator","status":"a e"}],
  ["300", {"code":"300","names":"ascorbic acid","type":"antioxidant (water-soluble)","status":"a e"}],
  ["301", {"code":"301","names":"sodium ascorbate","type":"antioxidant (water-soluble)","status":"a e"}],
  ["302", {"code":"302","names":"calcium ascorbate","type":"antioxidant (water-soluble)","status":"a e"}],
  ["303", {"code":"303","names":"potassium ascorbate","type":"antioxidant (water-soluble)","status":"a"}],
  ["304", {"code":"304","names":"ascorbyl palmitate, ascorbyl stearate","type":"antioxidant (fat soluble)","status":"a e"}],
  ["307", {"code":"307","names":"tocopherols","type":"","status":"a e"}],
  ["307a", {"code":"307a","names":"l-alpha-tocopherol","type":"antioxidant","status":"a e"}],
  ["307b", {"code":"307b","names":"mixed tocopherol concentrate","type":"antioxidant","status":"a e"}],
  ["307c", {"code":"307c","names":"dl-alpha-tocopherol","type":"antioxidant","status":"a e"}],
  ["308", {"code":"308","names":"gamma-tocopherol(synthetic)","type":"antioxidant","status":"a e"}],
  ["309", {"code":"309","names":"delta-tocopherol(synthetic)","type":"antioxidant","status":"a e"}],
  ["310", {"code":"310","names":"propyl gallate","type":"antioxidant","status":"a e u"}],
  ["311", {"code":"311","names":"octyl gallate","type":"antioxidant","status":"a e"}],
  ["312", {"code":"312","names":"dodecyl gallate","type":"antioxidant","status":"a e"}],
  ["315", {"code":"315","names":"erythorbic acid","type":"antioxidant","status":"a e"}],
  ["316", {"code":"316","names":"sodium erythorbate","type":"antioxidant","status":"a e"}],
  ["317", {"code":"317","names":"erythorbin acid","type":"antioxidant","status":""}],
  ["318", {"code":"318","names":"sodium erythorbin","type":"antioxidant","status":""}],
  ["319", {"code":"319","names":"tert-butylhydroquinone","type":"antioxidant","status":"a"}],
  ["320", {"code":"320","names":"butylated hydroxyanisole (BHA)","type":"antioxidant (fat soluble)","status":"a e u"}],
  ["321", {"code":"321","names":"butylated hydroxytoluene (BHT)","type":"antioxidant (fat soluble)","status":"a e u"}],
  ["322", {"code":"322","names":"lecithins","type":"antioxidant, emulsifier","status":"a e"}],
  ["325", {"code":"325","names":"sodium lactate","type":"food acid","status":"a e"}],
  ["326", {"code":"326","names":"potassium lactate","type":"food acid","status":"a e"}],
  ["327", {"code":"327","names":"calcium lactate","type":"food acid","status":"a e"}],
  ["328", {"code":"328","names":"ammonium lactate","type":"food acid","status":"a"}],
  ["329", {"code":"329","names":"magnesium lactate","type":"food acid","status":"a"}],
  ["330", {"code":"330","names":"citric acid","type":"food acid","status":"a e"}],
  ["331", {"code":"331","names":"sodium citrates","type":"food acid","status":"a e"}],
  ["332", {"code":"332","names":"potassium citrates","type":"food acid","status":"a e"}],
  ["333", {"code":"333","names":"calcium citrates","type":"food acid, firming agent","status":"a e"}],
  ["334", {"code":"334","names":"L(+)-tartaric acid","type":"food acid","status":"a e"}],
  ["335", {"code":"335","names":"sodium tartrates","type":"food acid","status":"a e"}],
  ["336", {"code":"336","names":"potassium tartrates","type":"food acid","status":"a e"}],
  ["337", {"code":"337","names":"potassium sodium tartrate","type":"food acid","status":"a e"}],
  ["338", {"code":"338","names":"phosphoric acid","type":"food acid","status":"a e"}],
  ["339", {"code":"339","names":"sodium phosphates","type":"mineral salt","status":"a e"}],
  ["340", {"code":"340","names":"potassium phosphates","type":"mineral salt","status":"a e"}],
  ["341", {"code":"341","names":"calcium phosphates","type":"mineral salt, anti-caking agent, firming agent","status":"a e"}],
  ["342", {"code":"342","names":"ammonium phosphates","type":"mineral salt","status":"a"}],
  ["343", {"code":"343","names":"magnesium phosphates","type":"mineral salt, anti-caking agent","status":"a e"}],
  ["344", {"code":"344","names":"lecithin citrate","type":"preservative","status":""}],
  ["345", {"code":"345","names":"magnesium citrate","type":"acidity regulator","status":""}],
  ["349", {"code":"349","names":"ammonium malate","type":"food acid","status":"a"}],
  ["350", {"code":"350","names":"sodium malates","type":"food acid","status":"a e"}],
  ["351", {"code":"351","names":"potassium malate","type":"food acid","status":"a e"}],
  ["352", {"code":"352","names":"calcium malates","type":"food acid","status":"a e"}],
  ["353", {"code":"353","names":"metatartaric acid","type":"food acid, emulsifier","status":"a e"}],
  ["354", {"code":"354","names":"calcium tartrate","type":"food acid, emulsifier","status":"a e"}],
  ["355", {"code":"355","names":"adipic acid","type":"food acid","status":"a e"}],
  ["356", {"code":"356","names":"sodium adipate","type":"food acid","status":"e"}],
  ["357", {"code":"357","names":"potassium adipate","type":"food acid","status":"a e"}],
  ["359", {"code":"359","names":"ammonium adipates","type":"acidity regulator","status":""}],
  ["363", {"code":"363","names":"succinic acid","type":"food acid","status":"e"}],
  ["364", {"code":"364","names":"sodium succinates","type":"acidity regulator, flavour enhancer","status":""}],
  ["365", {"code":"365","names":"sodium fumarate","type":"food acid","status":"a"}],
  ["366", {"code":"366","names":"potassium fumarate","type":"food acid","status":"a"}],
  ["367", {"code":"367","names":"calcium fumarate","type":"food acid","status":"a"}],
  ["368", {"code":"368","names":"ammonium fumarate","type":"food acid","status":"a"}],
  ["370", {"code":"370","names":"1,4-heptonolactone","type":"food acid","status":""}],
  ["375", {"code":"375","names":"niacin (nicotinic acid), nicotinamide (vitamin B3)","type":"colour retention agent","status":"a"}],
  ["380", {"code":"380","names":"triammonium citrate","type":"food acid","status":"a e"}],
  ["381", {"code":"381","names":"ferric ammonium citrate, ammonium ferrocitrate","type":"food acid","status":"a"}],
  ["384", {"code":"384","names":"isopropyl citrates","type":"antioxidant, preservative","status":""}],
  ["385", {"code":"385","names":"calcium disodium EDTA","type":"preservative","status":"a e"}],
  ["386", {"code":"386","names":"disodium ethylenediaminetetraacetate","type":"antioxidant, preservative","status":""}],
  ["387", {"code":"387","names":"oxystearin","type":"antioxidant, sequestrant","status":""}],
  ["388", {"code":"388","names":"thiodipropionic acid","type":"antioxidant","status":""}],
  ["389", {"code":"389","names":"dilauryl thiodipropionate","type":"antioxidant","status":""}],
  ["390", {"code":"390","names":"distearyl thiodipropionate","type":"antioxidant","status":""}],
  ["391", {"code":"391","names":"phytic acid","type":"preservative","status":""}],
  ["399", {"code":"399","names":"calcium lactobionate","type":"stabilizer","status":""}],
  ["400", {"code":"400","names":"alginic acid","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["401", {"code":"401","names":"sodium alginate","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["402", {"code":"402","names":"potassium alginate","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["403", {"code":"403","names":"ammonium alginate","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["404", {"code":"404","names":"calcium alginate","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["405", {"code":"405","names":"propylene glycol alginate, propane-1,2-diol alginate","type":"thickener, vegetable gum, stabilizer, emulsifier","status":"a e"}],
  ["406", {"code":"406","names":"agar","type":"thickener, vegetable gum, stabilizer, gelling agent","status":"a e"}],
  ["407", {"code":"407","names":"carrageenan","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e u"}],
  ["407a", {"code":"407a","names":"processed eucheuma seaweed","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["409", {"code":"409","names":"arabinogalactan","type":"thickener, vegetable gum","status":"a"}],
  ["410", {"code":"410","names":"locust bean gum","type":"thickener, vegetable gum, stabilizer, gelling agent, emulsifier","status":"a e"}],
  ["412", {"code":"412","names":"guar gum","type":"thickener, vegetable gum, stabilizer","status":"a e"}],
  ["413", {"code":"413","names":"tragacanth","type":"thickener, vegetable gum, stabilizer, emulsifier","status":"a e"}],
  ["414", {"code":"414","names":"gum acacia, gum arabic","type":"thickener, vegetable gum, stabilizer, emulsifier","status":"a e"}],
  ["415", {"code":"415","names":"xanthan gum","type":"thickener, vegetable gum, stabilizer","status":"a e"}],
  ["416", {"code":"416","names":"karaya gum","type":"thickener, vegetable gum, stabilizer, emulsifier","status":"a e"}],
  ["417", {"code":"417","names":"tara gum","type":"thickener, vegetable gum, stabilizer","status":"e"}],
  ["418", {"code":"418","names":"gellan gum","type":"thickener, vegetable gum, stabilizer, emulsifier","status":"a e"}],
  ["420", {"code":"420","names":"sorbitol","type":"humectant, emulsifier, sweetener","status":"a e"}],
  ["421", {"code":"421","names":"mannitol","type":"humectant, anti-caking agent, sweetener","status":"a e"}],
  ["422", {"code":"422","names":"glycerin","type":"humectant, sweetener","status":"a e"}],
  ["425", {"code":"425","names":"konjac, konjac gum, konjac glucomannate","type":"thickener, vegetable gum","status":"e"}],
  ["428", {"code":"428","names":"gelatin, gelatine (not classified as an additive)","type":"carrier, emulsifier, gelling agent, stabiliser, thickener","status":"a e u"}],
  ["430", {"code":"430","names":"polyoxyethylene (8) stearate","type":"emulsifier, stabilizer","status":""}],
  ["431", {"code":"431","names":"polyoxyethylene (40) stearate","type":"emulsifier","status":"e"}],
  ["432", {"code":"432","names":"polysorbate 20","type":"emulsifier","status":"e"}],
  ["433", {"code":"433","names":"polysorbate 80","type":"emulsifier","status":"a e"}],
  ["434", {"code":"434","names":"polysorbate 40","type":"emulsifier","status":"e"}],
  ["435", {"code":"435","names":"polysorbate 60","type":"emulsifier","status":"a e"}],
  ["436", {"code":"436","names":"polysorbate 65","type":"emulsifier","status":"a e"}],
  ["440", {"code":"440","names":"pectin","type":"vegetable gum, emulsifier","status":"a e"}],
  ["441", {"code":"441","names":"Superglycerinated hydrogenated rapeseed oil, Hydrogenated rapeseed oil superglycerinated, Superglycerinated fully hydrogenated rapeseed oil","type":"Emulsifier","status":"u"}],
  ["442", {"code":"442","names":"Mixed ammonium salts of phosphorylated glyceridess","type":"emulsifier","status":"a e"}],
  ["443", {"code":"443","names":"brominated vegetable oil","type":"emulsifier, stabiliser","status":""}],
  ["444", {"code":"444","names":"sucrose acetate isobutyrate","type":"emulsifier, stabiliser","status":"a e"}],
  ["445", {"code":"445","names":"glycerol esters of wood rosins","type":"emulsifier","status":"e"}],
  ["450", {"code":"450","names":"diphosphates","type":"mineral salt, emulsifier","status":"a e"}],
  ["451", {"code":"451","names":"triphosphates","type":"mineral salt, emulsifier","status":"a e"}],
  ["452", {"code":"452","names":"polyphosphates","type":"mineral salt, emulsifier","status":"a e"}],
  ["459", {"code":"459","names":"beta-cyclodextrin","type":"emulsifier","status":"e"}],
  ["460", {"code":"460","names":"powdered cellulose, microcrystalline cellulose","type":"anti-caking agent","status":"a e"}],
  ["461", {"code":"461","names":"methylcellulose","type":"thickener, emulsifier, vegetable gum","status":"a e"}],
  ["463", {"code":"463","names":"hydroxypropyl cellulose","type":"thickener, vegetable gum, emulsifier","status":"e"}],
  ["464", {"code":"464","names":"hydroxypropyl methylcellulose","type":"thickener, vegetable gum, emulsifier","status":"a e"}],
  ["465", {"code":"465","names":"methyl ethyl cellulose, ethyl methyl cellulose","type":"thickener, vegetable gum, emulsifier","status":"a e"}],
  ["466", {"code":"466","names":"sodium carboxymethylcellulose","type":"emulsifier","status":"a e"}],
  ["468", {"code":"468","names":"crosslinked sodium carboxymethylcellulose","type":"emulsifier","status":""}],
  ["469", {"code":"469","names":"enzymatically hydrolyzed carboxymethyl cellulose","type":"emulsifier","status":""}],
  ["470", {"code":"470","names":"magnesium stearate","type":"emulsifier, stabiliser","status":"a"}],
  ["470a", {"code":"470a","names":"sodium, potassium and calcium salts of fatty acids","type":"emulsifier, stabiliser, anti-caking agent","status":"e"}],
  ["470b", {"code":"470b","names":"magnesium salts of fatty acids","type":"emulsifier, stabiliser, anti-caking agent","status":"e"}],
  ["471", {"code":"471","names":"mono- and diglycerides of fatty acids – glyceryl monostearate, glyceryl distearate","type":"emulsifier","status":"a e"}],
  ["472a", {"code":"472a","names":"acetic acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"a e"}],
  ["472b", {"code":"472b","names":"lactic acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"a e"}],
  ["472c", {"code":"472c","names":"citric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"a e"}],
  ["472d", {"code":"472d","names":"tartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"a e"}],
  ["472e", {"code":"472e","names":"diacetyltartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"a e"}],
  ["472f", {"code":"472f","names":"mixed acetic and tartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["473", {"code":"473","names":"sucrose esters of fatty acids","type":"emulsifier","status":"a e"}],
  ["474", {"code":"474","names":"sucroglycerides","type":"emulsifier","status":"e"}],
  ["475", {"code":"475","names":"polyglycerol esters of fatty acids","type":"emulsifier","status":"a e"}],
  ["476", {"code":"476","names":"polyglycerol polyricinoleate","type":"emulsifier","status":"a e"}],
  ["477", {"code":"477","names":"propylene glycol esters of fatty acids","type":"emulsifier","status":"a e"}],
  ["478", {"code":"478","names":"lactylated fatty acid esters of glycerol and propylene glycol","type":"emulsifier","status":""}],
  ["479b", {"code":"479b","names":"thermally oxidised soya bean oil","type":"emulsifier","status":"e"}],
  ["480", {"code":"480","names":"dioctyl sodium sulfosuccinate","type":"emulsifier","status":"a"}],
  ["481", {"code":"481","names":"sodium stearoyl lactylate","type":"emulsifier","status":"a e"}],
  ["482", {"code":"482","names":"calcium stearoyl lactylate","type":"emulsifier","status":"a e"}],
  ["483", {"code":"483","names":"stearyl tartarate","type":"emulsifier","status":"e"}],
  ["491", {"code":"491","names":"sorbitan monostearate","type":"emulsifier","status":"a e"}],
  ["492", {"code":"492","names":"sorbitan tristearate","type":"emulsifier","status":"a e"}],
  ["493", {"code":"493","names":"sorbitan monolaurate","type":"emulsifier","status":""}],
  ["494", {"code":"494","names":"sorbitan monooleate","type":"emulsifier","status":"e"}],
  ["495", {"code":"495","names":"sorbitan monopalmitate","type":"emulsifier","status":"e"}],
  ["500", {"code":"500","names":"sodium carbonate, sodium bicarbonate (E500ii)","type":"mineral salt","status":"a e"}],
  ["501", {"code":"501","names":"potassium carbonate, potassium bicarbonate","type":"mineral salt","status":"a e"}],
  ["503", {"code":"503","names":"ammonium carbonate, ammonium bicarbonate","type":"mineral salt","status":"a e"}],
  ["504", {"code":"504","names":"magnesium carbonate","type":"anti-caking agent, mineral salt","status":"a e"}],
  ["507", {"code":"507","names":"hydrochloric acid","type":"acidity regulator","status":"a e"}],
  ["508", {"code":"508","names":"potassium chloride","type":"mineral salt","status":"a e"}],
  ["509", {"code":"509","names":"calcium chloride","type":"mineral salt","status":"a e"}],
  ["510", {"code":"510","names":"ammonium chloride","type":"mineral salt","status":"a"}],
  ["511", {"code":"511","names":"magnesium chloride","type":"mineral salt","status":"a e"}],
  ["512", {"code":"512","names":"stannous chloride","type":"colour retention agent, antioxidant","status":"a e"}],
  ["513", {"code":"513","names":"sulfuric acid","type":"acidity regulator","status":"e"}],
  ["514", {"code":"514","names":"sodium sulfate","type":"mineral salt","status":"a e"}],
  ["515", {"code":"515","names":"potassium sulfate","type":"mineral salt, seasoning","status":"a e"}],
  ["516", {"code":"516","names":"calcium sulfate","type":"flour treatment agent, mineral salt, sequestrant, improving agent, firming agent","status":"a e"}],
  ["517", {"code":"517","names":"ammonium sulfate","type":"mineral salt, improving agent","status":"e"}],
  ["518", {"code":"518","names":"magnesium sulfate, Epsom salts","type":"mineral salt, acidity regulator, firming agent","status":"a"}],
  ["519", {"code":"519","names":"cupric sulfate","type":"mineral salt","status":"a"}],
  ["520", {"code":"520","names":"aluminium sulfate","type":"mineral salt","status":"e"}],
  ["521", {"code":"521","names":"aluminium sodium sulfate","type":"mineral salt","status":"e"}],
  ["522", {"code":"522","names":"aluminium potassium sulfate","type":"mineral salt","status":"e"}],
  ["523", {"code":"523","names":"aluminium ammonium sulfate","type":"mineral salt","status":"e"}],
  ["524", {"code":"524","names":"sodium hydroxide","type":"mineral salt","status":"e"}],
  ["525", {"code":"525","names":"potassium hydroxide","type":"mineral salt","status":"e"}],
  ["526", {"code":"526","names":"calcium hydroxide","type":"mineral salt","status":"a e"}],
  ["527", {"code":"527","names":"ammonium hydroxide","type":"mineral salt","status":"e"}],
  ["528", {"code":"528","names":"magnesium hydroxide","type":"mineral salt","status":"e"}],
  ["529", {"code":"529","names":"calcium oxide","type":"mineral salt","status":"a e"}],
  ["530", {"code":"530","names":"magnesium oxide","type":"anti-caking agent","status":"e"}],
  ["535", {"code":"535","names":"sodium ferrocyanide","type":"anti-caking agent","status":"a e"}],
  ["536", {"code":"536","names":"potassium ferrocyanide","type":"anti-caking agent","status":"a e"}],
  ["538", {"code":"538","names":"calcium ferrocyanide","type":"anti-caking agent","status":"e"}],
  ["540", {"code":"540","names":"dicalcium diphosphate","type":"anti-caking agent","status":""}],
  ["541", {"code":"541","names":"sodium aluminium phosphate","type":"acidity regulator, emulsifier","status":"a e"}],
  ["542", {"code":"542","names":"bone phosphate","type":"anti-caking agent","status":"a"}],
  ["544", {"code":"544","names":"calcium polyphosphates","type":"anti-caking agent","status":""}],
  ["545", {"code":"545","names":"ammonium polyphosphates","type":"anti-caking agent","status":""}],
  ["551", {"code":"551","names":"silicon dioxide","type":"anti-caking agent","status":"a e"}],
  ["552", {"code":"552","names":"calcium silicate","type":"anti-caking agent","status":"a e"}],
  ["553a", {"code":"553a","names":"magnesium silicate","type":"anti-caking agent","status":"e"}],
  ["553b", {"code":"553b","names":"talc","type":"anti-caking agent","status":"a e"}],
  ["554", {"code":"554","names":"sodium aluminosilicate (sodium aluminium silicate)","type":"anti-caking agent","status":"a e"}],
  ["555", {"code":"555","names":"potassium aluminium silicate","type":"anti-caking agent","status":"e"}],
  ["556", {"code":"556","names":"calcium aluminosilicate (calcium aluminium silicate)","type":"anti-caking agent","status":"a e"}],
  ["558", {"code":"558","names":"bentonite","type":"anti-caking agent","status":"a e"}],
  ["559", {"code":"559","names":"kaolin, aluminium silicate","type":"anti-caking agent","status":"a e"}],
  ["570", {"code":"570","names":"stearic acid","type":"anti-caking agent","status":"a e"}],
  ["575", {"code":"575","names":"glucono delta-lactone","type":"acidity regulator","status":"a e"}],
  ["576", {"code":"576","names":"sodium gluconate","type":"stabiliser","status":"e"}],
  ["577", {"code":"577","names":"potassium gluconate","type":"stabiliser","status":"a e"}],
  ["578", {"code":"578","names":"calcium gluconate","type":"acidity regulator","status":"a e"}],
  ["579", {"code":"579","names":"ferrous gluconate","type":"colour retention agent","status":"a e"}],
  ["585", {"code":"585","names":"ferrous lactate","type":"","status":"e"}],
  ["620", {"code":"620","names":"glutamic acid","type":"flavour enhancer","status":"a e"}],
  ["621", {"code":"621","names":"monosodium glutamate (MSG)","type":"flavour enhancer","status":"a e"}],
  ["622", {"code":"622","names":"monopotassium glutamate","type":"flavour enhancer","status":"a e"}],
  ["623", {"code":"623","names":"calcium diglutamate","type":"flavour enhancer","status":"a e"}],
  ["624", {"code":"624","names":"monoammonium glutamate","type":"flavour enhancer","status":"a e"}],
  ["625", {"code":"625","names":"magnesium diglutamate","type":"flavour enhancer","status":"a e"}],
  ["626", {"code":"626","names":"guanylic acid","type":"flavour enhancer","status":""}],
  ["627", {"code":"627","names":"disodium guanylate","type":"flavour enhancer","status":"a e"}],
  ["628", {"code":"628","names":"dipotassium guanylate","type":"flavour enhancer","status":"e"}],
  ["629", {"code":"629","names":"calcium guanylate","type":"flavour enhancer","status":"e"}],
  ["630", {"code":"630","names":"inosinic acid","type":"flavour enhancer","status":"e"}],
  ["631", {"code":"631","names":"disodium inosinate","type":"flavour enhancer","status":"a e"}],
  ["632", {"code":"632","names":"dipotassium inosinate","type":"flavour enhancer","status":"e"}],
  ["633", {"code":"633","names":"calcium inosinate","type":"flavour enhancer","status":"e"}],
  ["634", {"code":"634","names":"calcium 5'-ribonucleotides","type":"flavour enhancer","status":"e"}],
  ["635", {"code":"635","names":"disodium 5'-ribonucleotides","type":"flavour enhancer","status":"a e"}],
  ["636", {"code":"636","names":"maltol","type":"flavour enhancer","status":"a"}],
  ["637", {"code":"637","names":"ethyl maltol","type":"flavour enhancer","status":"a"}],
  ["640", {"code":"640","names":"glycine","type":"flavour enhancer","status":"a e"}],
  ["641", {"code":"641","names":"leucine","type":"flavour enhancer","status":"a"}],
  ["650", {"code":"650","names":"zinc acetate","type":"flavour enhancer","status":"e"}],
  ["900", {"code":"900","names":"dimethylpolysiloxane","type":"emulsifier, anti-caking agent","status":"a e"}],
  ["901", {"code":"901","names":"beeswax","type":"glazing agent","status":"a e"}],
  ["902", {"code":"902","names":"candelilla wax","type":"glazing agent","status":"e"}],
  ["903", {"code":"903","names":"carnauba wax","type":"glazing agent","status":"a e"}],
  ["904", {"code":"904","names":"shellac","type":"glazing agent","status":"a e"}],
  ["905", {"code":"905","names":"paraffins","type":"glazing agent","status":"a e"}],
  ["907", {"code":"907","names":"refined microcrystalline wax","type":"glazing agent","status":""}],
  ["912", {"code":"912","names":"montanic acid esters","type":"humectant","status":"e"}],
  ["914", {"code":"914","names":"oxidised polyethylene wax","type":"humectant","status":"a e"}],
  ["920", {"code":"920","names":"L-cysteine","type":"flour treatment agent","status":"a e"}],
  ["924", {"code":"924","names":"potassium bromate","type":"flour treatment agent","status":"u"}],
  ["925", {"code":"925","names":"chlorine","type":"flour treatment agent","status":"a"}],
  ["926", {"code":"926","names":"chlorine dioxide","type":"flour treatment agent","status":"a"}],
  ["927b", {"code":"927b","names":"carbamide","type":"flour treatment agent","status":"e"}],
  ["928", {"code":"928","names":"benzoyl peroxide","type":"flour treatment agent","status":"a"}],
  ["938", {"code":"938","names":"argon","type":"propellant","status":"e"}],
  ["939", {"code":"939","names":"helium","type":"propellant","status":"e"}],
  ["941", {"code":"941","names":"nitrogen","type":"propellant","status":"a e"}],
  ["942", {"code":"942","names":"nitrous oxide","type":"propellant","status":"a e"}],
  ["943a", {"code":"943a","names":"butane","type":"propellant","status":"e"}],
  ["943b", {"code":"943b","names":"isobutane","type":"propellant","status":"e"}],
  ["950", {"code":"950","names":"Acesulfame potassium","type":"artificial sweetener","status":"a e"}],
  ["951", {"code":"951","names":"aspartame","type":"artificial sweetener","status":"a e"}],
  ["952", {"code":"952","names":"cyclamic acid, cyclamates","type":"artificial sweetener","status":"a e"}],
  ["953", {"code":"953","names":"isomalt","type":"humectant","status":"a e"}],
  ["954", {"code":"954","names":"saccharin","type":"artificial sweetener","status":"a e"}],
  ["955", {"code":"955","names":"sucralose","type":"artificial sweetener","status":"a"}],
  ["956", {"code":"956","names":"alitame","type":"artificial sweetener","status":"a"}],
  ["957", {"code":"957","names":"thaumatin","type":"flavour enhancer, artificial sweetener","status":"a e"}],
  ["959", {"code":"959","names":"neohesperidin dihydrochalcone","type":"artificial sweetener","status":"e"}],
  ["965", {"code":"965","names":"maltitol","type":"humectant, stabiliser","status":"a e"}],
  ["966", {"code":"966","names":"lactitol","type":"humectant","status":"a e"}],
  ["967", {"code":"967","names":"xylitol","type":"humectant, stabiliser","status":"a e"}],
  ["999", {"code":"999","names":"quillaia extract","type":"humectant","status":"e"}],
  ["1001", {"code":"1001","names":"choline salts and esters","type":"emulsifier","status":"a"}],
  ["1100", {"code":"1100","names":"amylases","type":"flour treatment agent","status":"a"}],
  ["1102", {"code":"1102","names":"glucose oxidase","type":"antioxidant","status":"a"}],
  ["1103", {"code":"1103","names":"invertase","type":"?","status":"e"}],
  ["1104", {"code":"1104","names":"lipases","type":"flavour enhancer","status":"a"}],
  ["1105", {"code":"1105","names":"lysozyme","type":"preservative","status":"a e"}],
  ["1200", {"code":"1200","names":"polydextrose","type":"humectant","status":"a e"}],
  ["1201", {"code":"1201","names":"poly vinyl pyrrolidone","type":"?","status":"a e"}],
  ["1202", {"code":"1202","names":"polyvinylpolypyrrolidone","type":"colour stabiliser","status":"a e"}],
  ["1400", {"code":"1400","names":"dextrin roasted starch","type":"thickener, vegetable gum","status":"a"}],
  ["1401", {"code":"1401","names":"acid treated starch","type":"thickener, vegetable gum","status":"a"}],
  ["1402", {"code":"1402","names":"alkaline treated starch","type":"thickener, vegetable gum","status":"a"}],
  ["1403", {"code":"1403","names":"bleached starch","type":"thickener, vegetable gum","status":"a"}],
  ["1404", {"code":"1404","names":"oxidised starch","type":"thickener, vegetable gum","status":"a e"}],
  ["1405", {"code":"1405","names":"enzyme treated starch","type":"thickener, vegetable gum","status":"a"}],
  ["1410", {"code":"1410","names":"monostarch phosphate","type":"thickener, vegetable gum","status":"a e"}],
  ["1412", {"code":"1412","names":"distarch phosphate","type":"thickener, vegetable gum","status":"a e"}],
  ["1413", {"code":"1413","names":"phosphated distarch phosphate","type":"thickener, vegetable gum","status":"a e"}],
  ["1414", {"code":"1414","names":"acetylated distarch phosphate","type":"thickener, vegetable gum","status":"a e"}],
  ["1420", {"code":"1420","names":"acetylated starch","type":"thickener, vegetable gum","status":"a e"}],
  ["1422", {"code":"1422","names":"acetylated distarch adipate","type":"thickener, vegetable gum","status":"a e"}],
  ["1440", {"code":"1440","names":"hydroxypropyl starch","type":"thickener, vegetable gum","status":"a e"}],
  ["1442", {"code":"1442","names":"hydroxypropyl distarch phosphate","type":"thickener, vegetable gum","status":"a e"}],
  ["1450", {"code":"1450","names":"starch sodium octenylsuccinate","type":"thickener, vegetable gum","status":"a e"}],
  ["1451", {"code":"1451","names":"acetylated oxidised starch","type":"thickener, vegetable gum","status":"e"}],
  ["1505", {"code":"1505","names":"triethyl citrate","type":"thickener, vegetable gum","status":"a e"}],
  ["1510", {"code":"1510","names":"ethanol (not classified as an additive)","type":"alcohol","status":""}],
  ["1518", {"code":"1518","names":"triacetin","type":"humectant","status":"a e"}],
  ["1520", {"code":"1520","names":"propylene glycol","type":"humectant","status":"a e"}],
  ["1521", {"code":"1521","names":"Polyethylene glycol[citation needed]","type":"antifoaming agent","status":"a"}],
]);
module.exports = CORPUS;
